- hosts: localhost
  tasks:
  - name: Check that you can connect (GET) to a page and it returns a status 200
    uri:
      url: "{{item}}"
      status_code: 200
    loop:
      - https://google.com
      - https://microsoft.com
      - http://ncodeit.com
      - https://ncodeit.com
      - www.ncodeit.com