- hosts: all
  tasks:
  - name: current host is {{ansible_hostname}}
    shell: echo "$HOSTNAME"
  - name: download the artifacts from the nexus
    get_url:
      url: "{{repo_url}}"
      dest: /tmp
      username: "{{nexus_username}}"
      password: "{{nexus_password}}"
      force: yes
  - name: deployment
    copy:
      src: {{war_file_name}}
      dest: /opt/tomcat85/webapps
      mode: u+rw,g-wx,o-rwx